[package]
name = "zokrates_baseline_zkp_wrapper"
version = "0.1.0"
authors = ["Kyle Thomas <kyle@provide.services>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
